version: "3.8"
services:
  backend:
    build: ./tienda-backend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: tiendauser
      DB_PASSWORD: tiendapass
      DB_NAME: tienda
      SESSION_SECRET: supersecretchangeme
      SESSION_TTL_HOURS: 24
      CORS_ORIGINS: http://localhost,http://localhost:80,http://localhost:5173
    volumes:
      - ./tienda-backend:/app
    depends_on:
      - db
  frontend:
    build:
      context: ./tienda-frontend
      args:
        VITE_API_BASE_URL: /api
    ports:
      - "80:80"
    environment:
      NODE_ENV: production
    volumes:
      - ./tienda-frontend:/app
    depends_on:
      - backend
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tienda
      MYSQL_USER: tiendauser
      MYSQL_PASSWORD: tiendapass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
